apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-orion
  namespace: prefect
  labels:
    app: prefect-orion
spec:
  selector:
    matchLabels:
      app: prefect-orion
  replicas: 1  # We're using SQLite, so we should only run 1 pod
  template:
    metadata:
      labels:
        app: prefect-orion
    spec:
      containers:
      - name: api
        image: prefecthq/prefect:2.6.9-python3.10
        command: ["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "WARNING"]
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 4200
        env:
          - name: PREFECT_API_URL
            value: https://prefect.sidhulabs.ca:4200/api
          
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-orion
  namespace: prefect
  labels:
    app: prefect-orion
spec:
  ports:
    - port: 4200
      protocol: TCP
  selector:
    app: prefect-orion
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orion
  namespace: prefect
spec:
  rules:
  - host: prefect.sidhulabs.ca
    http:
      paths:
      - backend:
          service:
            name: prefect-orion
            port:
              number: 4200
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.10.1.51
    - ip: 10.10.1.52
    - ip: 10.10.1.53
    - ip: 10.10.1.54

