---
apiVersion: v2
name: Jupyterhub Sub Chart 
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: jupyterhub
  version: 2.0.0
  repository: https://jupyterhub.github.io/helm-chart/
