api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: ashtontml@yahoo.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "8.8.8.8:53"
          - "8.8.4.4:53"
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
