apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage
  labels:
    app: mage
spec:
  selector:
    matchLabels:
      app: mage
  replicas: 1 
  template:
    metadata:
      labels:
        app: mage
    spec:
      containers:
      - name: mage
        image: mageai/mageai:latest
        command: ["mage", "start", "pipelines"]
        imagePullPolicy: "Always"
        ports:
          - containerPort: 6789
        volumeMounts:
        - name: mage-data
          mountPath: /home/src
      volumes:
        - name: mage-data
          persistentVolumeClaim:
            claimName: mage-data
---
apiVersion: v1
kind: Service
metadata:
  name: mage
  labels:
    app: mage
spec:
  ports:
    - port: 6789
      protocol: TCP
  selector:
    app: mage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mage
spec:
  rules:
  - host: mage.sidhulabs.ca
    http:
      paths:
      - backend:
          service:
            name: mage
            port:
              number: 6789
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.10.1.51
    - ip: 10.10.1.52
    - ip: 10.10.1.53
    - ip: 10.10.1.54
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mage-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 214748364800m
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-6ac5a07b-fd5c-41e2-85e2-26282caef5f4
