
traefik:
	ansible-playbook --inventory inventory.yml traefik.yml

eagent:
	ansible-playbook --inventory inventory.yml elastic-agent.yml

install:
	python3 -m pip install ansible
	brew install hudochenkov/sshpass/sshpass
