version: "3.3"
networks:
  spark-network:
services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    command: >
      /bin/sh -c '
      /spark/sbin/start-master.sh
      && tail -f /spark/logs/*'
    restart: unless-stopped
    ports:
      - 8082:8080
      - 7077:7077
      - 18080:18080
    networks:
      - spark-network
    volumes:
      - /media/sidhu:/media/sidhu
  spark-worker:
    build: .
    depends_on:
      - spark-master
    command: >
      /bin/sh -c '
      /spark/sbin/start-slave.sh $$SPARK_MASTER
      && tail -f /spark/logs/*'
    env_file:
      - spark-worker.env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    restart: unless-stopped
    ports:
      - 8080
    networks:
      - spark-network
    volumes:
      - /media/sidhu/:/media/sidhu
