apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env-configmap
data:
  EXECUTOR: "Kubernetes"
  LOAD_EX: "n"
  AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: '{"_request_timeout": [60,60]}'
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "bigsidhu/airflow-local"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "latest"
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: "airflow-env-configmap"
  AIRFLOW__KUBERNETES__GIT_SYNC_CREDENTIALS_SECRET: "git-credentials"
  AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow"
  AIRFLOW__KUBERNETES__GIT_REPO: https://www.github.com/Ashton-Sidhu/test_git_sync
  AIRFLOW__KUBERNETES__GIT_SYNC_ROOT: /git
  AIRFLOW__KUBERNETES__GIT_SYNC_DEST: sync
  AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
  AIRFLOW__KUBERNETES__GIT_SUBPATH: "dags"
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "default"
  AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs-pvc"
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/sync/dags"
