- name: Copy config files to node
  copy:
    src: "{{ item }}"
    dest: "$HOME"
  loop:
    - config.yml
    - traefik.yml

- name: Start Traefik with new config
  docker_compose:
    project_src: "$HOME"
    recreate: always
  register: output

- assert:
    that:
      - "services.traefik.traefik.state.running"
