---
services:
  # Configuration for Hub+Proxy
  jupyterhub:
    image: docker.io/bigsidhu/jupyterhub         # Build the container from this folder.
    container_name: jupyterhub   # The service will use this container name.
    environment:                     # Env variables passed to the Hub process.
      DOCKER_JUPYTER_IMAGE: docker.io/bigsidhu/jupyter-notebook:latest
      DOCKER_NETWORK_NAME: jupyterhub
      HUB_IP: jupyterhub
      LDAP_SERVER_ADDRESS: ad.sidhulabs.ca
      ADMIN_USERS: asidhu
    restart: unless-stopped
    ports: 
      - "8000:8000"
    volumes:                         # Give access to Docker socket.
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jupyterhub

networks:
  jupyterhub:
    driver: bridge
    external: true
