argo-cd:
  global:
    domain: argo.sidhulabs.ca
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      resource.ignoreResourceUpdatesEnabled: true
      resource.customizations.ignoreResourceUpdates.all: |
        jsonPointers:
          - /status
  server:
    ingress:
      enabled: true
