argo-cd:
  global:
    domain: argo.sidhulabs.ca
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      resource.ignoreResourceUpdatesEnabled: true
      resource.customizations.ignoreResourceUpdates.all: |
        jsonPointers:
          - /status
  server:
    ingress:
      enabled: true

  argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/sidhulabs/infra
            revision: &revision main
            directories:
              - path: apps/*
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: *revision
