---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.8.2
  count: 1
  secureSettings:
    - secretName: kibana-saved-objects-encrypted-key
  elasticsearchRef:
    name: elasticsearch
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://elastic.sidhulabs.ca:443"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.elastic.svc:8220"]
  
