name: Build JupyterLab Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated from v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Updated from v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated from v1
      - name: Login to DockerHub
        uses: docker/login-action@v3  # Updated from v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5  # Updated from v2
        with:
          context: docker-images/jupyterlab
          push: true
          tags: mdsiam07/jupyter-notebook:latest,mdsiam07/jupyter-notebook:${{ github.sha }}