name: Build MLFlow Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "docker-images/mlflow/**"
      - "!docker-images/mlflow/README.md"
      - "!docker-images/mlflow/docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker-images/mlflow
          push: true
          tags: bigsidhu/mlflow:latest,bigsidhu/mlflow:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
