name: Build MLFlow Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "docker-images/mlflow/**"
      - "!docker-images/mlflow/README.md"
      - "!docker-images/mlflow/docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Extract version string
        id: get_version
        run: |
          echo "CONTAINER_VERSION=$(cat docker-images/mlflow/Dockerfile | grep -E MLFLOW_VERSION\s?= | cut -d '=' -f 2)" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker-images/mlflow
          push: true
          tags: bigsidhu/mlflow:${{ env.CONTAINER_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
