---
- name: Install k3s Load Balancer
  hosts: k3s_load_balancer
  tasks:
    - name: Copy load balancer config
      copy:
        src: nginx.conf
        dest: /home/sidhu/nginx.conf
    
    - name: Start docker nginx
      docker_container:
        name: nginx
        image: nginx:latest
        ports:
          - 80:80
          - 443:443
          - 6443:6443
          - 8220:8220
          - 9200:9200
        restart_policy: unless-stopped
        volumes: /home/sidhu/nginx.conf:/etc/nginx/nginx.conf
